# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: thesunsak
# 파일 이름: serverless.yml

# 1. 서비스 이름 정의
service: sunsaktool-renderer

# 2. 사용할 Serverless Framework 버전 지정

# 3. 클라우드 제공사(Provider) 및 환경 설정
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2 # AWS 서울 리전

# 4. 우리가 배포할 함수(기능) 목록
functions:
  renderVideo:
    handler: rendering-server/handler.main
