# 파일 이름: serverless.yml (CORS 해결 최종 버전)

service: sunsaktool-renderer
frameworkVersion: '^4'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  
  # ✨ CORS 문제를 해결하기 위한 설정 추가 ✨
  httpApi:
    cors: true # 이 한 줄이 마법입니다!

functions:
  renderVideo:
    handler: rendering-server/handler.main
    timeout: 900
    memorySize: 2048
    events:
      - httpApi:
          path: /render-video
          method: post
