# 파일 이름: serverless.yml (권한 문제 해결 최종 버전)

service: sunsaktool-renderer
frameworkVersion: '^4'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2

functions:
  renderVideo:
    handler: rendering-server/handler.main
    timeout: 900
    memorySize: 2048
    layers:
      - arn:aws:lambda:ap-northeast-2:145266761615:layer:ffmpeg-6-20230522:1
    events:
      # httpApi 대신 http를 사용하고, cors를 여기에 설정하는 것이 더 안정적입니다.
      - http:
          path: /render-video
          method: post
          cors: true
